services:

  backend_service:
    build: .
    env_file: .env
    command: uv run uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - postgres_service
  postgres_service:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: 1
    ports:
      - "5433:5432"
#volumes:
#  postgres_data: